import moment from 'moment';

export const currencies = [
  { title: 'Favoritter', onlyTitle: true },
  { name: "Dansk Krone", identification: "DKK" },
  { name: "Amerikansk Dollar", identification: "USD" },
  { name: "Euro", identification: "EUR" },
  { name: "Britisk Pound Sterling", identification: "GBP" },
  { title: 'Verden', onlyTitle: true },
  { name: "Afghansk Afghani", identification: "AFN" },
  { name: "Albansk Lek", identification: "ALL" },
  { name: "Armenisk Dram", identification: "AMD" },
  { name: "Hollandske Gulden", identification: "ANG" },
  { name: "Angolansk Kwanza", identification: "AOA" },
  { name: "Argentinsk Peso", identification: "ARS" },
  { name: "Australsk Dollar", identification: "AUD" },
  { name: "Arubansk Florin", identification: "AWG" },
  { name: "Aserbajdsjansk Manat", identification: "AZN" },
  { name: "Bosnisk-Hercegovinsk Convertible Mark", identification: "BAM" },
  { name: "Barbados Dollar", identification: "BBD" },
  { name: "Bangladesh Taka", identification: "BDT" },
  { name: "Bulgarisk Lev", identification: "BGN" },
  { name: "Bahrainsk Dinar", identification: "BHD" },
  { name: "Burundiansk Franc", identification: "BIF" },
  { name: "Bermudansk Dollar", identification: "BMD" },
  { name: "Bruneiansk Dollar", identification: "BND" },
  { name: "Boliviansk Boliviano", identification: "BOB" },
  { name: "Brasiliansk Real", identification: "BRL" },
  { name: "Bahamansk Dollar", identification: "BSD" },
  { name: "Bhutanese Ngultrum", identification: "BTN" },
  { name: "Botswansk Pula", identification: "BWP" },
  { name: "Beliziansk Dollar", identification: "BZD" },
  { name: "Kanadisk Dollar", identification: "CAD" },
  { name: "Congolesisk Franc", identification: "CDF" },
  { name: "Schweizisk Franc", identification: "CHF" },
  { name: "Chilensk Enhed af Regnskab UF", identification: "CLF" },
  { name: "Chilensk Peso", identification: "CLP" },
  { name: "Kinesisk Yuan Offshore", identification: "CNH" },
  { name: "Kinesisk Yuan", identification: "CNY" },
  { name: "Colombiansk Peso", identification: "COP" },
  { name: "Cubansk Peso", identification: "CUP" },
  { name: "Kap Verde Escudo", identification: "CVE" },
  { name: "Tjekkisk Koruna", identification: "CZK" },
  { name: "Djiboutiansk Franc", identification: "DJF" },
  { name: "Dominikansk Peso", identification: "DOP" },
  { name: "Algerisk Dinar", identification: "DZD" },
  { name: "Egyptisk Pound", identification: "EGP" },
  { name: "Eritreansk Nakfa", identification: "ERN" },
  { name: "Etiopisk Birr", identification: "ETB" },
  { name: "Fijiansk Dollar", identification: "FJD" },
  { name: "Forenede Arabiske Emirater Dirham", identification: "AED" },
  { name: "Falklandsøerne Pound", identification: "FKP" },
  { name: "Georgisk Lari", identification: "GEL" },
  { name: "Ghanesisk Cedi", identification: "GHS" },
  { name: "Gibraltar Pound", identification: "GIP" },
  { name: "Gambiansk Dalasi", identification: "GMD" },
  { name: "Guineansk Franc", identification: "GNF" },
  { name: "Guatemalansk Quetzal", identification: "GTQ" },
  { name: "Guyanesisk Dollar", identification: "GYD" },
  { name: "Hongkong Dollar", identification: "HKD" },
  { name: "Honduransk Lempira", identification: "HNL" },
  { name: "Kroatisk Kuna", identification: "HRK" },
  { name: "Haitiansk Gourde", identification: "HTG" },
  { name: "Ungarsk Forint", identification: "HUF" },
  { name: "Indonesisk Rupiah", identification: "IDR" },
  { name: "Indisk Rupee", identification: "INR" },
  { name: "Irakisk Dinar", identification: "IQD" },
  { name: "Iransk Rial", identification: "IRR" },
  { name: "Islandsk Krona", identification: "ISK" },
  { name: "Jamaicansk Dollar", identification: "JMD" },
  { name: "Jordanisk Dinar", identification: "JOD" },
  { name: "Japansk Yen", identification: "JPY" },
  { name: "Kenyansk Shilling", identification: "KES" },
  { name: "Kyrgystansk Som", identification: "KGS" },
  { name: "Cambodjansk Riel", identification: "KHR" },
  { name: "Komorisk Franc", identification: "KMF" },
  { name: "Nordkoreansk Won", identification: "KPW" },
  { name: "Sydkoreansk Won", identification: "KRW" },
  { name: "Kuwaitisk Dinar", identification: "KWD" },
  { name: "Cayman Dollar", identification: "KYD" },
  { name: "Kasakhisk Tenge", identification: "KZT" },
  { name: "Laotisk Kip", identification: "LAK" },
  { name: "Libanesisk Pound", identification: "LBP" },
  { name: "Sri Lankansk Rupee", identification: "LKR" },
  { name: "Liberiansk Dollar", identification: "LRD" },
  { name: "Basotho Maloti", identification: "LSL" },
  { name: "Libysk Dinar", identification: "LYD" },
  { name: "Marokkansk Dirham", identification: "MAD" },
  { name: "Moldovansk Leu", identification: "MDL" },
  { name: "Malagassisk Ariary", identification: "MGA" },
  { name: "Makedonsk Denar", identification: "MKD" },
  { name: "Myanma Kyat", identification: "MMK" },
  { name: "Mongolsk Tugrik", identification: "MNT" },
  { name: "Macanesisk Pataca", identification: "MOP" },
  { name: "Mauritansk Ouguiya", identification: "MRU" },
  { name: "Mauritiansk Rupee", identification: "MUR" },
  { name: "Maldiviansk Rufiyaa", identification: "MVR" },
  { name: "Malawiansk Kwacha", identification: "MWK" },
  { name: "Mexicansk Peso", identification: "MXN" },
  { name: "Malaysisk Ringgit", identification: "MYR" },
  { name: "Mozambikansk Metical", identification: "MZN" },
  { name: "Namibisk Dollar", identification: "NAD" },
  { name: "Nigeriansk Naira", identification: "NGN" },
  { name: "Norsk Krone", identification: "NOK" },
  { name: "Nepali Rupee", identification: "NPR" },
  { name: "New Zealandsk Dollar", identification: "NZD" },
  { name: "Omanisk Rial", identification: "OMR" },
  { name: "Panamansk Balboa", identification: "PAB" },
  { name: "Peruviansk Nuevo Sol", identification: "PEN" },
  { name: "Papua Ny Guinea Kina", identification: "PGK" },
  { name: "Filippinsk Peso", identification: "PHP" },
  { name: "Pakistansk Rupee", identification: "PKR" },
  { name: "Polsk Zloty", identification: "PLN" },
  { name: "Paraguayansk Guarani", identification: "PYG" },
  { name: "Qatarisk Rial", identification: "QAR" },
  { name: "Rumænsk Leu", identification: "RON" },
  { name: "Serbisk Dinar", identification: "RSD" },
  { name: "Russisk Rubel", identification: "RUB" },
  { name: "Rwandisk Franc", identification: "RWF" },
  { name: "Saudiarabisk Riyal", identification: "SAR" },
  { name: "Seychellisk Rupee", identification: "SCR" },
  { name: "Sudanesisk Pound", identification: "SDG" },
  { name: "Svensk Krone", identification: "SEK" },
  { name: "Singapore Dollar", identification: "SGD" },
  { name: "Saint Helena Pound", identification: "SHP" },
  { name: "Sierra Leonean Leone", identification: "SLL" },
  { name: "Somalisk Shilling", identification: "SOS" },
  { name: "Surinamsk Dollar", identification: "SRD" },
  { name: "Syrisk Pound", identification: "SYP" },
  { name: "Swaziland Emalangeni", identification: "SZL" },
  { name: "Thailandsk Baht", identification: "THB" },
  { name: "Tadsjikistani Somoni", identification: "TJS" },
  { name: "Turkmenske Manat", identification: "TMT" },
  { name: "Tunisisk Dinar", identification: "TND" },
  { name: "Tongansk Pa'anga", identification: "TOP" },
  { name: "Tyrkisk Lira", identification: "TRY" },
  { name: "Trinidad og Tobago Dollar", identification: "TTD" },
  { name: "Taiwan New Dollar", identification: "TWD" },
  { name: "Tanzanisk Shilling", identification: "TZS" },
  { name: "Ukrainsk Hryvnia", identification: "UAH" },
  { name: "Ugandisk Shilling", identification: "UGX" },
  { name: "Uruguayan Peso", identification: "UYU" },
  { name: "Usbekistan Som", identification: "UZS" },
  { name: "Vietnamesisk Dong", identification: "VND" },
  { name: "Ni-Vanuatu Vatu", identification: "VUV" },
  { name: "Samoansk Tala", identification: "WST" },
  { name: "CFA Franc BEAC", identification: "XAF" },
  { name: "Østcaribisk Dollar", identification: "XCD" },
  { name: "Særlige Trækretter", identification: "XDR" },
  { name: "CFA Franc BCEAO", identification: "XOF" },
  { name: "CFP Franc", identification: "XPF" },
  { name: "Yemenitisk Rial", identification: "YER" },
  { name: "Sydafrikansk Rand", identification: "ZAR" },
  { name: "Zambiansk Kwacha", identification: "ZMW" },
]

export const countries = [
  { title: 'Favoritter' },
  "Danmark",
  { title: 'Verden' },
  "Afghanistan",
  "Ålandsøerne",
  "Albanien",
  "Algeriet",
  "Amerikansk Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarktis",
  "Antigua og Barbuda",
  "Argentina",
  "Armenien",
  "Aruba",
  "Australien",
  "Østrig",
  "Aserbajdsjan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Hviderusland",
  "Belgien",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnien-Hercegovina",
  "Botswana",
  "Bouvetøen",
  "Brasilien",
  "Britiske Territorium i Det Indiske Ocean",
  "Brunei Darussalam",
  "Bulgarien",
  "Burkina Faso",
  "Burundi",
  "Cambodja",
  "Cameroon",
  "Canada",
  "Kap Verde",
  "Caymanøerne",
  "Centralafrikanske Republik",
  "Tchad",
  "Chile",
  "Kina",
  "Juleøen",
  "Cocosøerne (Keelingøerne)",
  "Colombia",
  "Comorerne",
  "Congo",
  "Congo, Den Demokratiske Republik Congo",
  "Cookøerne",
  "Costa Rica",
  "Elfenbenskysten",
  "Kroatien",
  "Cuba",
  "Curaçao",
  "Cypern",
  "Tjekkiet",
  "Djibouti",
  "Dominica",
  "Dominikanske Republik",
  "Ecuador",
  "Egypten",
  "El Salvador",
  "Ækvatorial Guinea",
  "Eritrea",
  "Estland",
  "Etiopien",
  "Falklandsøerne (Malvinas)",
  "Færøerne",
  "Fiji",
  "Finland",
  "Frankrig",
  "Fransk Guiana",
  "Fransk Polynesien",
  "Franske Sydlige Territorier",
  "Gabon",
  "Gambia",
  "Georgien",
  "Tyskland",
  "Ghana",
  "Gibraltar",
  "Grækenland",
  "Grønland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard- og McDonald-øerne",
  "Vatikanstaten",
  "Honduras",
  "Hongkong",
  "Ungarn",
  "Island",
  "Indien",
  "Indonesien",
  "Iran, Den Islamiske Republik",
  "Irak",
  "Irland",
  "Isle of Man",
  "Italien",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kasakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Den Demokratiske Folkerepublik Korea",
  "Korea, Republikken Korea",
  "Kuwait",
  "Kirgisistan",
  "Lao Folkets Demokratiske Republik",
  "Letland",
  "Libanon",
  "Lesotho",
  "Liberia",
  "Libysk Arabisk Jamahiriya",
  "Liechtenstein",
  "Litauen",
  "Luxembourg",
  "Macao",
  "Makedonien, Den Tidligere Jugoslaviske Republik",
  "Madagaskar",
  "Malawi",
  "Malaysia",
  "Maldiverne",
  "Mali",
  "Malta",
  "Marshalløerne",
  "Martinique",
  "Mauretanien",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Mikronesien, De Forenede Stater",
  "Moldova, Republikken",
  "Monaco",
  "Mongoliet",
  "Montenegro",
  "Montserrat",
  "Marokko",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nederlandene",
  "Ny Caledonien",
  "New Zealand",
  "Nikaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Nordmarianerne",
  "Norge",
  "Oman",
  "Pakistan",
  "Palau",
  "Palæstina",
  "Panama",
  "Papua Ny Guinea",
  "Paraguay",
  "Peru",
  "Filippinerne",
  "Pitcairn",
  "Polen",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Réunion",
  "Rumænien",
  "Rusland",
  "Rwanda",
  "Saint Helena",
  "Saint Kitts og Nevis",
  "Saint Lucia",
  "Saint Pierre og Miquelon",
  "Saint Vincent og Grenadinerne",
  "Samoa",
  "San Marino",
  "Sao Tome og Principe",
  "Senegal",
  "Serbien",
  "Seychellerne",
  "Sierra Leone",
  "Singapore",
  "Slovakiet",
  "Slovenien",
  "Salomonøerne",
  "Somalia",
  "Sydafrika",
  "South Georgia og South Sandwich Islands",
  "Spanien",
  "Sri Lanka",
  "Sudan",
  "Surinam",
  "Svalbard og Jan Mayen",
  "Eswatini",
  "Sverige",
  "Schweiz",
  "Syriske Arabiske Republik",
  "Taiwan (ROC)",
  "Tadsjikistan",
  "Tanzania, Forenede Republik af",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad og Tobago",
  "Tunesien",
  "Tyrkiet",
  "Turkmenistan",
  "Turks- og Caicosøerne",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "Storbritannien",
  "USA",
  "Amerikansk oversøisk samfund",
  "Uruguay",
  "Usbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Jomfruøerne, Britiske",
  "Jomfruøerne, U.S.",
  "Wallis og Futuna",
  "Vestlige Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
]

export const unitTypes = [
  { name: "None", identification: null },
  { name: "Kilogram (kg)", identification: "kg" },
  { name: "Gram (g)", identification: "g" },
  { name: "Pound (lb)", identification: "lb" },
  { name: "Ounce (oz)", identification: "oz" },
  { name: "Liter (L)", identification: "L" },
  { name: "Milliliter (ml)", identification: "ml" },
  { name: "Gallon (gal)", identification: "gal" },
  { name: "Dozen (dz)", identification: "dz" },
  { name: "Each (ea)", identification: "ea" },
  { name: "Piece (pc)", identification: "pc" },
  { name: "Unit (u)", identification: "u" },
  { name: "Meter (m)", identification: "m" },
  { name: "Centimeter (cm)", identification: "cm" },
  { name: "Square Meter (m²)", identification: "m²" },
  { name: "Square Foot (ft²)", identification: "ft²" },
  { name: "Cubic Meter (m³)", identification: "m³" },
  { name: "Cubic Foot (ft³)", identification: "ft³" },
  { name: "Hour (hr)", identification: "hr" },
  { name: "Minute (min)", identification: "min" },
  { name: "Second (s)", identification: "s" },
  { name: "Day (day)", identification: "day" },
  { name: "Week (wk)", identification: "wk" },
  { name: "Month (mo)", identification: "mo" },
  { name: "Year (yr)", identification: "yr" },
  { name: "Package (pkg)", identification: "pkg" },
  { name: "Carton (ctn)", identification: "ctn" },
  { name: "Case (cs)", identification: "cs" },
  { name: "Pallet (pl)", identification: "pl" },
  { name: "Roll (roll)", identification: "roll" },
  { name: "Set (set)", identification: "set" },
  { name: "Bundle (bdl)", identification: "bdl" },
  { name: "Pair (pr)", identification: "pr" },
  { name: "Ton (t)", identification: "t" },
  { name: "Bushel (bu)", identification: "bu" },
  { name: "Square Inch (in²)", identification: "in²" },
  { name: "Square Yard (yd²)", identification: "yd²" },
  { name: "Cubic Inch (in³)", identification: "in³" },
  { name: "Cubic Yard (yd³)", identification: "yd³" },
  { name: "Barrel (bbl)", identification: "bbl" },
  { name: "Gallon (US) (gal)", identification: "gal (US)" },
  { name: "Gallon (UK) (gal)", identification: "gal (UK)" },
  { name: "Hectare (ha)", identification: "ha" },
  { name: "Acre (ac)", identification: "ac" },
  { name: "Dozen (doz)", identification: "doz" },
  { name: "Gross (gr)", identification: "gr" },
  { name: "Gross (great gross) (gr. gr.)", identification: "gr. gr." },
  { name: "Thousand (M)", identification: "M" },
  { name: "Million (MM)", identification: "MM" },
  { name: "Billion (B)", identification: "B" },
  { name: "Score (sc)", identification: "sc" },
  { name: "Hundred (C)", identification: "C" },
  { name: "Sheet (sheet)", identification: "sheet" },
  { name: "Ream (ream)", identification: "ream" }
];

export function correctDate(date, defaultFormat = 'YYYY-MM-DD') {
  let year = null;
  let month = null;
  let day = null;

  // Find the separator
  const separator = date.includes('/') ? '/' :
      (date.includes('-') ? '-' :
          (date.includes('.') ? '.' :
              (date.includes(' ') ? ' ' : null)));

  if (!separator) {
      return null;
  }

  const dateArray = date.split(separator);

  // Find if year contains 4 digits
  dateArray.forEach((value, index) => {
      if (value.length === 4) {
          year = value;
          dateArray.splice(index, 1);
      }
  });

  if (!year) {
      year = dateArray[2];
      dateArray.splice(2, 1);
  }

  dateArray.forEach((value, index) => {
      if (value.length === 3) {
          month = value;
          dateArray.splice(index, 1);
      }
  });

  if (dateArray.length === 1) {
      day = dateArray[0];
  }

  if (!month) {
      if (parseInt(dateArray[0]) > 12) {
          day = dateArray[0];
          month = dateArray[1];
      } else if (parseInt(dateArray[1]) > 12) {
          day = dateArray[1];
          month = dateArray[0];
      }
  }

  if (!month) {
      month = dateArray[0];
      day = dateArray[1];
  }
  if (!year || !month || !day || isNaN(year) || isNaN(month) || isNaN(day)) {
    return null;
  }

  // Convert to Moment.js format
  return moment({ year: parseInt(year), month: parseInt(month) - 1, day: parseInt(day) }).isValid()
      ? moment({ year: parseInt(year), month: parseInt(month) - 1, day: parseInt(day) }).format(defaultFormat)
      : null;
}

export function printCurrency(currency) {
  if (currency === 'DKK') return 'kr.';
  
  return currency;
}

export function textColorWhiteOrBlack(color) {
  // Ensure the color is a hex value and remove the leading "#"
  const hexColor = color.replace("#", "");
  
  // Convert the hex to RGB values
  const r = parseInt(hexColor.substring(0, 2), 16);
  const g = parseInt(hexColor.substring(2, 4), 16);
  const b = parseInt(hexColor.substring(4, 6), 16);

  // Calculate the brightness based on the RGB values
  const brightness = (0.299 * r + 0.587 * g + 0.114 * b);

  // Return the appropriate class based on brightness
  return brightness > 145 ? "text-black" : "text-white";
};

export const times = Array.from({ length: 96 }, (_, i) => {
  const hour = Math.floor(i / 4).toString().padStart(2, '0');
  const minute = ((i % 4) * 15).toString().padStart(2, '0');
  const time = `${hour}:${minute}`;
  
  return { value: time };
});

export const taskColors = ['#0EAAE9', '#1AAF62', '#38BDF8', '#10B981', '#F59E0B', '#F43F5E', '#8B5CF6', '#64748B', '#84CC16', '#06B6D4', '#EC4899', '#14B8A6'];
